### ISSUE TITLE
Fix tooltip flickering on hover

### ISSUE THREAD

**Issue by FajarMaftuhFadli** [moalamri/vscode-inline-fold#23]
When we hover into the fold, the tool-tip should be stay right? But in my case, the hover tool-tip is only visible for a moment.

**Comment by moalamri** [comment]
Hey @FajarMaftuhFadli 
I'm aware of this. The reason is because this is not a built-in API, it's a hacky way I used to mock the folding experience, which goes as the following:
- Text get matched.
- A custom decorator is used for the matched text which set the letterspacing to `-1 ch` (ch = character) & and used css style to set `display: none`
- The letters are overlapping each other into `-1 ch` and are basically hidden.
- I used a decorator option (before) which insert text at the beginning as a "mask".
- I exposed the other decorator option (after) so the user can append any custom text.
So, in this case there's no text to hover 😄 it's only possible when hovering unfolded content.

Anyways, I've thought of a way to enable tooltip when hovering on folded content, but it will require to add a third decorator (because there are two decorators already)
I'm afraid that it might be laggy or that it will cause flickering when the visible range changes.

I will convert this issue to a task for the upcoming update. You can unsubscribe if it annoys you 😀

**Comment by FajarMaftuhFadli** [comment]
That is nice to know, I hope it's going well

**Comment by moalamri** [comment]
Hey @FajarMaftuhFadli 
I'm afraid it's impossible for the moment. I tried my solution and it didn't work.
Perhaps it can work, but it will require the extension to write real text which is a bad idea (a bad regex could overwrite your whole code)
So I'm closing this feature for now. I hope I could find a way in future.

**Comment by FajarMaftuhFadli** [comment]
> Hey @FajarMaftuhFadli I'm afraid it's impossible for the moment. I tried my solution and it didn't work. Perhaps it can work, but it will require the extension to write real text which is a bad idea (a bad regex could overwrite your whole code) So I'm closing this feature for now. I hope I could find a way in future.

Would it be possible to disable that tooltip while hovering over a fold and only enable it when unfolded? As a result, there is no flashing tooltip visible.

**Comment by moalamri** [comment]
Yes it is possible and already applied it to the upcoming update 👍
