### ISSUE TITLE
Create a toggle button to open and fold className

### ISSUE THREAD

**Issue by ZaikoXander** [moalamri/vscode-inline-fold#26]
I think must be interesting to have an option in the extension that when enabled, at the left of a `className` should have a toggle button to open and fold that `className`.

**Comment by moalamri** [comment]
Hey @ZaikoXander 
Thanks for the suggestion.
Unfortunately since this is not a real API, and is basically a hacky way I used around existing APIs, the `before` decoration is used to display the "mask" that covers the "folded" content, therefore there's no way of doing that, but there's an option `"inlineFold.after"` you can use that to display any desired character right after the folded content.

**Comment by ZaikoXander** [comment]
Thanks for answering, and I'll be waiting for the update 😁✌
