### ISSUE TITLE
Color preview box

### ISSUE THREAD

**Issue by babakfp** [moalamri/vscode-inline-fold#28]
I'm not sure whether this is fixable or not🤷‍♂️

![Screenshot 2022-07-19 124448](https://user-images.githubusercontent.com/44144724/179836055-e1367bd5-5d97-4014-929c-2f698f049894.png)

**Comment by moalamri** [comment]
Hi @babakfp 
In the next update you will be able to apply custom styling 👍

**Comment by babakfp** [comment]
Hey
Oops, I meant the square color box is still visible.
![Screenshot 2022-07-19 124448](https://user-images.githubusercontent.com/44144724/179943862-3b3731fa-8485-4a88-9a43-9840870eade1.png)

**Comment by moalamri** [comment]
I got you now 👍
There is no possible way I could think of to fix that, because it's probably applied by another extension which is something I can't prevent from my side. There's an extension that applies the color previous instead of the color selection box. Maybe it's a good replacement?
Plus if you are using Tailwind css, it's better to put colors in the framework's configs file, that way it also won't interfere with this extension or any other decorators.

**Comment by moalamri** [comment]
Feel free to reopen if needed
