### ISSUE TITLE
Classes "flash"

### ISSUE THREAD

**Issue by Auxtal** [moalamri/vscode-inline-fold#58]
Heya, I notice that when I scroll very quickly in a file the classes are like normal and then quickly get "folded". I'm not sure if this behaviour is expected I assume it is, but it's very annoying, is there any way you can stop this from occurring?

The same happens when loading a file I.E clicking on a file in the side bar and the editor opens.

**Comment by moalamri** [comment]
Hi @Auxtal 
For the initial folding it is something beyond the extension as the editor will load things accordingly where text decoration is the last thing (which the extension part is).
As for fast scrolling I’ve already submitted a [bug report](https://github.com/microsoft/vscode/issues/154977)  in VSCode repository.
It happens because the extension’s debouncer takes half a second to process the correct visible range while scrolling. And if you may wonder why not apply the decoration to the whole document instead of the visible range + a preset offset  is because a misconfigured regex could simply crash VS Code if applied to huge files as some users have experienced.

**Comment by Auxtal** [comment]
Oh ok, thanks for that information, appreciate it :)
