### ISSUE TITLE
feature-request: Add an option for fold more than a number of characters/classes

### ISSUE THREAD

**Issue by SeyyedKhandon** [moalamri/vscode-inline-fold#74]
Because this plugin folds everything by default, it's hard to scan the codes by a glance because people usually need to scan what the code was for...
![image](https://user-images.githubusercontent.com/59599950/204301340-bf1f3d55-75e4-4ca7-b56a-bfb075a0b1de.png)

Currently, I have written a regex for myself that can be easily set as a new option in this plugin.

```
(class|className)=(({(`|))|(['"`]))(([^"`']){40,})(.)(\2|(\4)})
```

![image](https://user-images.githubusercontent.com/59599950/204303349-665b6dbe-cf2e-41a9-acb6-ddc1ecdbd8be.png)

And another great option will be showing the  3 classes(less or more based on the option that user has been set) shows those number of classes and the rest will be under `...` 
this can led people to use the meaningful class names at first for checking it via at a glance and it can be really helpful.

**Comment by moalamri** [comment]
hi @SeyyedKhandon 
Thanks for the suggestion, sure the extension could be a barrier when styling, which is why I added an option `default state` and registered a keyboard shortcut `Inline Fold: Toggle` which will toggle folding `on: off` per file. It will be handy when working with styling (class values). And toggle the folding back when working on the page text or any other attributes.

There's an example at the [main page](https://github.com/moalamri/vscode-inline-fold/) for different use cases and settings with one that suggest for folding after a set number of characters.

**Comment by SeyyedKhandon** [comment]
Hi dear @moalamri ,
Thank you, turning it on/off is a great option when actively working on a file, but in practice we use lots of scanning which can be really help-full as you can see the page is not bloated by long classes lines:

![image](https://user-images.githubusercontent.com/59599950/204322629-50f30e49-9359-4760-bdd7-2dac9d97abb3.png)


Also these options will make the developer experience great:

- folding more than a number of character/classes 
- showing the 3 classes(less or more based on the option that user has been set) shows those number of classes and the rest will be under `...`
- by default show classes on the selected line or a scope of its direct parents  `"inlineFold.unfoldOnLineSelect": true`
- by default unfolded opacity to be normal `"inlineFold.unfoldedOpacity": 1`


ps. actually it is very great by default and thank you for this useful plugin, but it can be better in case of developer experience

**Comment by moalamri** [comment]
Just a side note: I must be honest the screenshots made me confused since they actually have some content mismatching 😅

Anyways, I fully get your point now. You might wonder why not so much options regarding the matched contents, it was because I either use regex or use a code walker (which will give me the flexibility to tweak lots of settings), but, a code walker must be language aware. Which is impossible for me to implement. So i will just use regex and add a language scoped settings, because a user might set folding after 2 words, which is something that will break folding in markdown links for example.

**Comment by SeyyedKhandon** [comment]
thank you🙏

**Comment by moalamri** [comment]
@SeyyedKhandon 
You're welcome, I guess this will be enhanced when #27 is fixed.
In that case you could use the suggested regex at the main page for specific languages to support folding after set number of characters without breaking the folding in other languages.
I will close this and feel free to reopen if needed 👍🏻
